### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, tuple found

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/worldengine#103]
(venv)bcurtis@Wintermute:~/workspace/WorldEngine/worldengine-gui$ python worldengine-gui/__main__.py 
Traceback (most recent call last):
  File "worldengine-gui/__main__.py", line 530, in _on_open
    world = World.open_protobuf(filename)
  File "/home/bcurtis/workspace/WorldEngine/worldengine/worldengine/world.py", line 71, in open_protobuf
    with open(filename, "rb") as f:
TypeError: coercing to Unicode: need string or buffer, tuple found
Traceback (most recent call last):
  File "worldengine-gui/__main__.py", line 530, in _on_open
    world = World.open_protobuf(filename)
  File "/home/bcurtis/workspace/WorldEngine/worldengine/worldengine/world.py", line 71, in open_protobuf
    with open(filename, "rb") as f:
TypeError: coercing to Unicode: need string or buffer, tuple found

**Comment by ftomassetti** [comment]
This is the method where the error happens
```python
    @staticmethod
    def open_protobuf(filename):
        with open(filename, "rb") as f:
            content = f.read()
            return World.protobuf_unserialize(content)
```

**Comment by psi29a** [comment]
For the GUI, no longer a problem in WE.
