### ISSUE TITLE
Investigate crashes due to usage of grayscale-heightmap and rivers options

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#113]
whenever I use the parameters --grayscale-heightmap="..." or --rivers="..." the program crashes with the following output (of course I didn't just put in "..."):

--Linux output:
Producing ouput:
* world data saved in '../generated_worlds/1616896804/1616896804.world'
* ocean image generated in '../generated_worlds/1616896804/1616896804_ocean.png'
* precipitation image generated in '../generated_worlds/1616896804/1616896804_precipitation.png'
* temperature image generated in '../generated_worlds/1616896804/1616896804_temperature.png'
* biome image generated in '../generated_worlds/1616896804/1616896804_biome.png'
* elevation image generated in '../generated_worlds/1616896804/1616896804_elevation.png'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/home/bcurtis/workspace/WorldEngine/worldengine/build/WE/out00-PYZ.pyz/cli.main", line 444, in main
  File "/home/bcurtis/workspace/WorldEngine/worldengine/build/WE/out00-PYZ.pyz/cli.main", line 71, in generate_grayscale_heightmap
  File "/home/bcurtis/workspace/WorldEngine/worldengine/build/WE/out00-PYZ.pyz/worldengine.draw", line 394, in draw_grayscale_heightmap_on_file
  File "/home/bcurtis/workspace/WorldEngine/worldengine/build/WE/out00-PYZ.pyz/worldengine.draw", line 145, in complete
  File "/home/bcurtis/workspace/WorldEngine/worldengine/build/WE/out00-PYZ.pyz/PIL.Image", line 1678, in save
KeyError: ''

--Windows output:
Producing ouput:
* world data saved in '../generated_worlds/695750035/695750035.world'
* ocean image generated in '../generated_worlds/695750035/695750035_ocean.png'
* precipitation image generated in '../generated_worlds/695750035/695750035_precipitation.png'
* temperature image generated in '../generated_worlds/695750035/695750035_temperature.png'
* biome image generated in '../generated_worlds/695750035/695750035_biome.png'
* elevation image generated in '../generated_worlds/695750035/695750035_elevation.png'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\workspace\worldengine\build\worldengine\out00-PYZ.pyz\cli.main", line 444, in main
  File "C:\workspace\worldengine\build\worldengine\out00-PYZ.pyz\cli.main", line 71, in generate_grayscale_heightmap
  File "C:\workspace\worldengine\build\worldengine\out00-PYZ.pyz\worldengine.draw", line 394, in draw_grayscale_heightmap_on_file
  File "C:\workspace\worldengine\build\worldengine\out00-PYZ.pyz\worldengine.draw", line 145, in complete
  File "C:\workspace\worldengine\build\worldengine\out00-PYZ.pyz\PIL.Image", line 1678, in save
KeyError: ''

**Comment by psi29a** [comment]
This looks like fun... pay no attention to the paths, that isn't the problem.

@ftomassetti  have you managed to reproduce this (binary and straight from source).

**Comment by ftomassetti** [comment]
nope, I did not tried yet

**Comment by psi29a** [comment]
Isn't a crash, but rather PILLOW (PIL) that only looks at the extension of the filename to determine what format to save the image (river or greyscale) to.  So a bad extension 'crap' from "blah.crap" will throw a keyerror because `crap` doesn't exist.

I catch this error, and append a 'png' along with an message saying why.

I also try looking for '.' in the filename at the start and verify it exists, otherwise error out with message why.

**Comment by ftomassetti** [comment]
Thanks!
