### ISSUE TITLE
Loading HDF5-Worlds

### ISSUE THREAD

**Issue by tcld** [Mindwerks/worldengine#206]
Since now there is a way to save worlds in HDF5-format...[shouldn't there be a way to load it](https://github.com/Mindwerks/worldengine/blob/master/worldengine/cli/main.py#L198), too?^^

When I recently looked at that code I just assumed that there was some way that I just overlooked...but actually no, [the *user* cannot load HDF5-worlds](https://github.com/Mindwerks/worldengine/blob/master/worldengine/cli/main.py#L17). Small oversight? :P

```bash
(venv3)tcl@tcl-main:/Worldengine/worlds/13051_hdf5 (318s)$ worldengine info seed_13051.world 
Unable to load GDAL support, no heightmap export possible.
Worldengine - a world generator (v. 0.18.0)
-----------------------
Traceback (most recent call last):
  File "venv3/bin/worldengine", line 9, in <module>
    load_entry_point('worldengine==0.18.0', 'console_scripts', 'worldengine')()
  File "venv3/lib/python3.4/site-packages/worldengine-0.18.0-py3.4.egg/worldengine/cli/main.py", line 605, in main
    world = load_world(args.FILE)
  File "venv3/lib/python3.4/site-packages/worldengine-0.18.0-py3.4.egg/worldengine/cli/main.py", line 215, in load_world
    raise Exception("The given worldfile does not seem to be a protobuf file")
Exception: The given worldfile does not seem to be a protobuf file
```

**Comment by ftomassetti** [comment]
Wonderful, we will fix that in 0.18.1
