### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by burakk** [Mindwerks/worldengine#213]
Hi, I am using mac os x. I am getting the following output with python 3.5. 

(python3.5.0)Buraks-MacBook-Pro:python3.5.0 burakk$ worldengine ancient_map -w an_example.world
Traceback (most recent call last):
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/bin/worldengine", line 7, in <module>
    from worldengine.cli.main import main
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/lib/python3.5/site-packages/worldengine/cli/main.py", line 6, in <module>
    import worldengine.generation as geo
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/lib/python3.5/site-packages/worldengine/generation.py", line 2, in <module>
    from worldengine.world import Step
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/lib/python3.5/site-packages/worldengine/world.py", line 15, in <module>
    import worldengine.protobuf.World_pb2 as Protobuf
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/lib/python3.5/site-packages/worldengine/protobuf/World_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/lib/python3.5/site-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 846
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

**Comment by psi29a** [comment]
That is just evil, protobuf strikes again!  Looks like it use the old-style exceptions. We can help put pressure on protobuf to fix this.

In the mean time, we can try to catch it ourselves but we can't know what the original message was.

Might ask, the "an_example.world"... was that also created by python3.5 or was this from a previous version of WE?

**Comment by tcld** [comment]
What version of Worldengine are you even using? The most recent one?

**Comment by burakk** [comment]
I have installed it via pip. I think it is the production version.

**Comment by tcld** [comment]
That means version 0.18; I had a lot of problems installing that version, I expect 0.19 to fix the problems for you. And hopefully 0.19 will be released soon. ;)

**Comment by psi29a** [comment]
try `worldengine --version`

**Comment by ftomassetti** [comment]
Version 0.19.0 is on pypi

**Comment by burakk** [comment]
thanx !:)

**Comment by psi29a** [comment]
Can this be closed?

**Comment by anshuman73** [comment]
Hi, is this issue still open ?
What's the decision ? What to do if this can be fixed ?
