### ISSUE TITLE
IndexError: index 5000 is out of bounds for axis 1 with size 5000

### ISSUE THREAD

**Issue by MarkDerosier** [Mindwerks/worldengine#233]
```
Worldengine - a world generator (v. 0.19.0)
-----------------------
 operation              : ancient_map generation
 resize factor          : 1
 world file             : worldofethos.world
 sea color              : brown
 draw biome             : True
 draw rivers            : True
 draw mountains         : True
 draw land outer border : False

```

```
starting (it could take a few minutes) ...
Traceback (most recent call last):
  File "<string>", line 619, in <module>
  File "<string>", line 586, in main
  File "<string>", line 143, in operation_ancient_map
  File "/media/workspace/WorldEngine/worldengine/worldengine/draw.py", line 804, in draw_ancientmap_on_file
  File "/media/workspace/WorldEngine/worldengine/worldengine/drawing_functions.py", line 833, in draw_ancientmap
  File "/media/workspace/WorldEngine/worldengine/worldengine/drawing_functions.py", line 215, in _draw_temperate_forest1
  File "/media/workspace/WorldEngine/worldengine/worldengine/image_io.py", line 224, in __setitem__
IndexError: index 5000 is out of bounds for axis 1 with size 5000
main returned -1
```

While most my errors have be from just running out of memory while generating worlds, this happened after I was able to successfully generate a world using

`worldengine --not-fade-borders world -r -s 51293 -n worldofethos -q 80 -x 5000 -y 5000
`

But trying to generate an ancient_map caused the above error. This is on Debian 8.5 jessie, using a build from the release page. 

CPU: Intel Xeon CPU E3-1245 v3 @ 3.8GHz
32171MB of Ram
x86_64 Linux 3.16.0-4-amd64

if that should matter. 

(note I was able to generate a world and a map with the same argument, except with 4,000 instead of 5,000)

**Comment by psi29a** [comment]
I'll have a look when I have time. Thanks for bringing this to our attention. :)

**Comment by psi29a** [comment]
So after many years... nearly a decade? 

Anyway, as of the recent release, 0.20 we can no longer reproduce this issue:

```
(venv) ➜  /tmp venv/bin/worldengine --not-fade-borders world -r -s 51293 -n worldofethos -q 80 -x 5000 -y 5000  ancient_map
Worldengine - a world generator (v. 0.20.0)
-----------------------
 operation            : world generation
 seed                 : 51293
 name                 : worldofethos
 width                : 5000
 height               : 5000
 number of plates     : 80
 world format         : protobuf
 black and white maps : False
 step                 : full
 greyscale heightmap  : False
 icecaps heightmap    : False
 rivers map           : True
 scatter plot         : False
 satellite map        : False
 fade borders         : False
 gamma value          : 1.25
 gamma offset         : 0.2

starting (it could take a few minutes) ...

Producing ouput:
* world data saved in './worldofethos.world'
* ocean image generated in './worldofethos_ocean.png'
* precipitation image generated in './worldofethos_precipitation.png'
* temperature image generated in './worldofethos_temperature.png'
* biome image generated in './worldofethos_biome.png'
* elevation image generated in './worldofethos_elevation.png'
+ rivers map generated in './worldofethos_rivers.png'
...done
(venv) ➜  /tmp 
```

:)

**Comment by MarkDerosier** [comment]
How the time does pass! Thank you, I hope you weren't working on it the whole time! I suppose I'll have to go see what the map looks like now.
