### ISSUE TITLE
AttributeError: 'World' object has no attribute

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#235]
_From an e-mail of a user_

Hi,

I have 2 Problems, 

if i generate a world with "-ice", I get

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\cli.main", line 559, in main
  File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\cli.main", line 101, in draw_icecaps_map
  File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\worldengine.draw", line 824, in draw_icecaps_on_file
AttributeError: 'World' object has no attribute 'icecap'

and if i export a world (without -ice), I get

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\cli.main", line 600, in main
  File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\worldengine.imex", line 95, in export
AttributeError: 'World' object has no attribute 'elevation'

I think its the same issue, both methods use the old attribute not the layer.

It would be very nice if somebody can fix it and create a new release because i can't install it from source. I need the windows executable.

Thanks

**Comment by c-w** [comment]
@ftomassetti: I submitted a fix for this issue in #237 -- could you please take a look?
