### ISSUE TITLE
Installed Lands; won't run. "DLL load failed:%1 is not a valid Win32 application."

### ISSUE THREAD

**Issue by Chilangosta** [Mindwerks/worldengine#51]
I've been trying to run Lands for several days now, but I keep running into issues. I'm a newbie with Python (and coding in general), but I think I've installed it just fine. When I try to run it I get the following error:

````
C:\Users\User\Downloads\Lands\Lands-master>lands world -s 1 -n seed1
Traceback (most recent call last):
    File "C:\Python27\Scripts\lands-script.py", line 9, in <module>
        load_entry_point('lands==0.5.3.1', 'console_scripts', 'lands')()
    File "C:\Python27\lib\site-packages\pkg_resources.py", line 339, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
    File "C:\Python27\lib\site-packages\pkg_resources.py", line 2470, in load_entry_point
        return ep.load()
    File "C:\Python27\lib\site-packages\\pkg_resources.py", line 2184, in load 
        ['__name__'])
    File "C:\Python27\lib\site-packages\lands\generator.py", line 8, in <module>
        import lands.geo
    File "C:\Python27\lib\site-packages\lands\geo.py", line 4, in <module>
        from noise import snoise2
    File "C:\Python27\lib\site-packages\noise\__init__.py", line 12, in <module>
        from . import _perlin, _simplex
ImportError: DLL load failed: %1 is not a valid Win32 application.
````

I followed the wiki's instructions for installing on Windows, and I made sure I had 64-bit versions of everything (e.g. Python 2.7.9, pip, etc.) Let me know if I'm missing any important info.

**Comment by Chilangosta** [comment]
Nevermind; I just updated to the latest version and installed it, and I don't have this problem anymore - I have a different one :). I'll use the google group though to bring it up!

**Comment by ftomassetti** [comment]
Sorry about the problem and thank you for your patience, as soon as I grab a windows machine I will try to figure out what is going on. We are working on a better windows experience for the future but for now let's fix your issues
