### ISSUE TITLE
Precipitation error on the GUI

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#57]
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\worldenginegui-script.py", line 9, in <module>
    load_entry_point('worldengine==0.5.4', 'console_scripts', 'worldenginegui')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2310, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build\bdist.win-amd64\egg\worldengine\gui\main.py", line 27, in <module>
ImportError: No module named views.PrecipitationsView
```

As reported by Ryan

**Comment by ftomassetti** [comment]
Moved to https://github.com/Mindwerks/worldengine-gui/issues/8
