### ISSUE TITLE
PyPy bug in generating biome map.

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/worldengine#92]
Producing ouput:
* world data saved in './seed_1563.world'
* ocean image generated in './seed_1563_ocean.png'
* precipitation image generated in './seed_1563_precipitation.png'
* temperature image generated in './seed_1563_temperature.png'
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/usr/lib/pypy/lib-python/2.7/runpy.py", line 164, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/pypy/lib-python/2.7/runpy.py", line 73, in _run_code
    exec code in run_globals
  File "/media/workspace/WorldEngine/worldengine/worldengine/__main__.py", line 2, in <module>
    main.main()
  File "worldengine/cli/main.py", line 413, in main
    options.verbose, black_and_white=options.black_and_white)
  File "worldengine/cli/main.py", line 59, in generate_world
    draw_biome_on_file(w, filename)
  File "/media/workspace/WorldEngine/worldengine/worldengine/draw.py", line 426, in draw_biome_on_file
    draw_biome(world, img)
  File "/media/workspace/WorldEngine/worldengine/worldengine/draw.py", line 366, in draw_biome
    target.set_pixel(x, y, _biome_colors[v])
  File "/media/workspace/WorldEngine/worldengine/worldengine/draw.py", line 139, in set_pixel
    self.pixels[x, y] = color
  File "/media/workspace/WorldEngine/worldengine/pypyvenv/site-packages/PIL/PyAccess.py", line 72, in __setitem__
    return self.set_pixel(x, y, color)
  File "/media/workspace/WorldEngine/worldengine/pypyvenv/site-packages/PIL/PyAccess.py", line 147, in set_pixel
    pixel.a = min(color[3], 255)
IndexError: tuple index out of range

**Comment by psi29a** [comment]
Fixed in this commit:
https://github.com/Mindwerks/worldengine/commit/1a8839a772a88101caee9b72c9cf8f7d5b08de62

**Comment by ftomassetti** [comment]
then I will close this one
